"""admin column added

Revision ID: 7ad4ac7a484a
Revises: a2c18debff5b
Create Date: 2024-12-16 15:06:35.175025

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '7ad4ac7a484a'
down_revision = 'a2c18debff5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isadmin', sa.Boolean(), nullable=False), schema='university')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isadmin', schema='university')
    # ### end Alembic commands ###
